client_config_backend: file
client_config:
    client_id: 193154842370-1n25hjvh3hr4597c1760mpglf1jjph0l.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive